server:
  port: 20000

spring:
  redis:
    host: 192.168.2.4
    database: 1
    connect-timeout: 20000
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
